In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from lmfit import models

Vendor:  Continuum Analytics, Inc.
Package: mkl
Message: trial mode expires in 30 days


# Reflextion

## 70nm

In [2]:
# erst parallel dann senkrecht
data_angle_70nm = np.array([37.2,45,52.06,44,46,48,42,39,50])
data_70nm = [np.array([0.62,0.88,0.7,0.84,0.9,0.85,0.76,0.61,0.73]),np.array([0.68,0.8,0.79,0.8,0.8,0.8,0.76,0.66,0.78])]
data_70nm = np.array(data_70nm)

In [3]:
mask_70nm = np.argsort(data_angle_70nm)

In [4]:
plt.plot(data_angle_70nm[mask_70nm],data_70nm[0][mask_70nm]/data_70nm[1][mask_70nm], '-p')
plt.show()

## 30nm

In [5]:
data_angle_30nm = np.array([37.2,45,52.06,44,46,48,42,39,50,46,40,41,43,39.5,40.5,43.5,38,44.5,44.25,43.75])
data_30nm = [np.array([0.05,0.59,0.53,0.63,0.57,0.55,0.90,0.05,0.53,0.57,0.29,0.72,0.76,0.12,0.49,0.66,0.03,0.61,0.56,0.63]),np.array([0.74,0.69,0.65,0.69,0.68,0.64,0.71,0.74,0.65,0.68,0.73,0.72,0.67,0.73,0.72,0.68,0.75,0.69,0.62,0.68])]
data_30nm = np.array(data_30nm)

In [6]:
mask_30nm = np.argsort(data_angle_30nm)

In [7]:
plt.plot(data_angle_30nm[mask_30nm],data_30nm[0][mask_30nm]/data_30nm[1][mask_30nm], '-p')
plt.show()

## 40nm

In [8]:
# erst parallel dann senkrecht
data_angle_40nm = np.array([37.2,45,52.06,44,46,48,42,39,50])
data_40nm = [np.array([0.31,0.3,0.62,0.26,0.46,0.94,0.26,0.30,0.70]),np.array([0.78,0.72,0.67,0.71,0.71,0.69,0.73,0.74,0.69])]
data_40nm = np.array(data_40nm)

In [9]:
mask_40nm = np.argsort(data_angle_40nm)

In [10]:
plt.plot(data_angle_40nm[mask_40nm],data_40nm[0][mask_40nm]/data_40nm[1][mask_40nm], '-p')
plt.show()

## 50nm

In [11]:
data_angle_50nm = np.arange(38,59)

In [12]:
data_50nm = [np.array([0.49,0.49,0.48,0.48,0.48,0.49,0.52,0.62,0.84,0.98,0.91,0.78,0.72,0.71,0.70,0.70,0.69,0.68,0.67,0.66,0.66]),
             np.array([0.83,0.82,0.82,0.82,0.82,0.81,0.81,0.80,0.80,0.80,0.79,0.78,0.78,0.78,0.77,0.77,0.77,0.76,0.72,0.73,0.73])]

In [13]:
plt.plot(data_angle_50nm, data_50nm[0]/data_50nm[1], '--p', label="50nm")
plt.xlabel(r'Winkel$^\circ$')
plt.legend(loc='best')
plt.show()

## Plot

# set tick width
plt.rcParams['xtick.major.size'] = 10
plt.rcParams['xtick.major.width'] = 2
plt.rcParams['xtick.minor.size'] = 5
plt.rcParams['xtick.minor.width'] = 1

plt.rcParams['ytick.major.size'] = 10
plt.rcParams['ytick.major.width'] = 2
plt.rcParams['ytick.minor.size'] = 5
plt.rcParams['ytick.minor.width'] = 1

In [14]:
from matplotlib.ticker import AutoMinorLocator, MultipleLocator


In [15]:
plt.plot(data_angle_50nm, data_50nm[0]/data_50nm[1], '--p', label="Schichtdicke: 50nm")
plt.plot(data_angle_30nm[mask_30nm], data_30nm[0][mask_30nm]/data_30nm[1][mask_30nm], '--h', label="Schichtdicke: 30nm")
plt.plot(data_angle_40nm[mask_40nm], data_40nm[0][mask_40nm]/data_40nm[1][mask_40nm], '-p', label="Schichtdicke: 40nm")
plt.plot(data_angle_70nm[mask_70nm], data_70nm[0][mask_70nm]/data_70nm[1][mask_70nm], '-h', label="Schichtdicke: 70nm")
plt.xlabel(r'Winkel / $^\circ$', fontsize=24)
plt.ylabel(r'$R_p/R_s$', fontsize=24)
plt.xticks(fontsize=18)
plt.yticks(fontsize=18)

#plt.grid()

ml = MultipleLocator(0.5)
plt.axes().xaxis.set_minor_locator(ml)
#plt.axes().yaxis.set_minor_locator(ml)

plt.legend(loc='best')
plt.show()

# Sputtern

In [16]:
(79*17+16*45)/124

16.637096774193548

In [17]:
(45*15.5+45*15+20*15.75)/110

15.340909090909092

In [18]:
(45*15+45*15+4*15)/95

14.842105263157896

In [19]:
(45*15+30*14.75+15)/76

14.901315789473685

In [20]:
(45*15+12*15)/57

15.0

# Brewsterwinkel

In [21]:
brewster_winkel = np.arange(70,115,5)
brewster_winkel = np.append(brewster_winkel,[88,86,92,94,90,88,90,88,90,92,86])

In [22]:
brewster_intensity = np.array([14.5,7,2.3,-0.5,-1.6,-0.2,4.1,9.9,17.5,-1.7,-1,-0.9,-0.2,-1.4,-1.4,-1.3,-1.2,-1.2,-0.7,-0.7])

## Sortieren der arrays nach den Winkeln

In [23]:
sorted_intensity = brewster_intensity[np.argsort(brewster_winkel)[::-1]]
sorted_winkel = brewster_winkel[np.argsort(brewster_winkel)[::-1]]

In [24]:
sorted_intensity

array([ 17.5,   9.9,   4.1,  -0.2,  -0.2,  -0.9,  -0.7,  -1.2,  -1.3,
        -1.4,  -1.6,  -1.7,  -1.2,  -1.4,  -0.7,  -1. ,  -0.5,   2.3,
         7. ,  14.5])

In [25]:
sorted_winkel

array([110, 105, 100,  95,  94,  92,  92,  90,  90,  90,  90,  88,  88,
        88,  86,  86,  85,  80,  75,  70])

In [26]:
plt.plot(sorted_winkel,sorted_intensity, '--h', label='Messdaten')
plt.xlabel(r'Winkel / $^\circ$', fontsize=24)
plt.ylabel(r'Spannung / V', fontsize=24)
plt.xticks(fontsize=18)
plt.yticks(fontsize=18)
plt.xlim([69,111])
plt.show()

In [27]:
def brewster_fit(x,I_0,b,a):
    return I_0 * np.cos(a*x)**2 - b

In [28]:
mod_brewster = models.Model(brewster_fit)
pars_brewster = mod_brewster.make_params()
pars_brewster['I_0'].set(-12.7)
pars_brewster['b'].set(-10.8)
pars_brewster['a'].set(0.03)

In [29]:
out_brewster = mod_brewster.fit(sorted_intensity, pars_brewster, x=sorted_winkel, weights=1/0.3)

In [30]:
print(out_brewster.fit_report())

[[Model]]
    Model(brewster_fit)
[[Fit Statistics]]
    # function evals   = 39
    # data points      = 20
    # variables        = 3
    chi-square         = 18.102
    reduced chi-square = 1.065
[[Variables]]
    I_0:  -40.6605753 +/- 0.524713 (1.29%) (init=-12.7)
    b:    -39.1790128 +/- 0.487223 (1.24%) (init=-10.8)
    a:     0.03530955 +/- 3.92e-05 (0.11%) (init= 0.03)
[[Correlations]] (unreported correlations are <  0.100)
    C(I_0, b)                    =  0.990 
    C(b, a)                      =  0.277 
    C(I_0, a)                    =  0.256 



In [31]:
out_brewster.plot_fit()
plt.show()

In [32]:
plt.errorbar(sorted_winkel,sorted_intensity, yerr=0.3, fmt=' h', label='Messdaten')
plt.plot(np.arange(60,121),out_brewster.eval(x=np.arange(60,121)),label='Fit')
plt.xlabel(r'Winkel / $^\circ$', fontsize=24)
plt.ylabel(r'Spannung / mV', fontsize=24)
plt.xticks(fontsize=18)
plt.yticks(fontsize=18)
plt.xlim([69,111])
plt.ylim([-5,20])
plt.legend(loc='upper center', fontsize=34)
plt.show()

# Reflexions messung Philipp und Jens

In [212]:
r_data_18nm = pd.read_csv("18nm_data", delim_whitespace=True)
r_data_36nm = pd.read_csv("36nm_data", delim_whitespace=True)
r_data_63nm = pd.read_csv("63nm_data", delim_whitespace=True)
r_data_45nm = pd.read_csv("45nm_data", delim_whitespace=True)
r_data_27nm = pd.read_csv("27nm_data", delim_whitespace=True)
r_data_err_18nm = pd.read_csv("18nm_data_err", delim_whitespace=True, header=None)
r_data_err_36nm = pd.read_csv("36nm_data_err", delim_whitespace=True, header=None)
r_data_err_63nm = pd.read_csv("63nm_data_err", delim_whitespace=True, header=None)
r_data_err_45nm = pd.read_csv("45nm_data_err", delim_whitespace=True, header=None)
r_data_err_27nm = pd.read_csv("27nm_data_err", delim_whitespace=True, header=None)

In [213]:
data_list = [r_data_18nm,r_data_27nm,r_data_36nm,r_data_45nm,r_data_63nm]

In [214]:
data_err_list = [r_data_err_18nm,r_data_err_27nm,r_data_err_36nm,r_data_err_45nm,r_data_err_63nm]

In [215]:
r_data_18nm.columns = ['theta_ein','theta_aus','beta','alpha','up','us','ps']
r_data_27nm.columns = ['theta_ein','theta_aus','beta','alpha','up','us','ps']
r_data_36nm.columns = ['theta_ein','theta_aus','beta','alpha','up','us','ps']
r_data_45nm.columns = ['theta_ein','theta_aus','beta','alpha','up','us','ps']
r_data_63nm.columns = ['theta_ein','theta_aus','beta','alpha','up','us','ps']

In [218]:
for i,j in zip(data_list,data_err_list):
    print(i.ps.size, j.size)

19 19
22 22
18 18
19 19
19 19


In [211]:
r_data_18nm[['alpha','ps']]

alpha        ps
0   50.270818  0.029268
1   49.942497  0.024470
2   49.613961  0.021277
3   49.285226  0.018152
4   48.956305  0.013333
5   48.627213  0.011686
6   48.297964  0.008475
7   47.639053  0.008636
8   46.979687  0.021201
9   46.319981  0.050269
10  45.660047  0.108059
11  45.000000  0.216165
12  44.339953  0.406375
13  43.680019  0.755382
14  43.020313  1.287726
15  41.702036  2.269912
16  40.386039  1.130120
17  51.581665  0.053208
18  58.047330  0.150072

In [102]:
for data_set in data_list:
    data_set.sort('alpha', inplace=True)

/home/frederik/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:2: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  from ipykernel import kernelapp as app


In [103]:
for data_set,dicke in zip(data_list,[18,27,36,45,63]):
    plt.plot(data_set.alpha,data_set.ps, '-h', label=str(dicke)+' Schichtdicke')
plt.legend()
plt.show()

In [100]:
def reflexion_fit(x,a,b,c,d,e):
    return a*(1-(b+c*(x-d))/((x-d)**2+e**2))

In [232]:
def x_min(b,c,d,e):
    return d+(-b+(b**2+c**2*e**2)**0.5)/c

In [109]:
mod_reflex = models.Model(reflexion_fit)
pars_reflex = mod_reflex.make_params()

 - Adding parameter "a"
 - Adding parameter "b"
 - Adding parameter "c"
 - Adding parameter "d"
 - Adding parameter "e"


In [128]:
pars_reflex['a'].set(0.9)
pars_reflex['b'].set(0.3)
pars_reflex['c'].set(1)
pars_reflex['d'].set(43)
pars_reflex['e'].set(-1)

In [238]:
from matplotlib.pyplot import cm 

color=iter(cm.rainbow(np.linspace(0,1,5)))


for data_set,data_err,dicke in zip(data_list[0:2],data_err_list[0:2],[18,27]):
    c=next(color)
    out_reflex = mod_reflex.fit(data_set.ps[data_set.alpha > 42],pars_reflex,x=data_set.alpha[data_set.alpha > 42], weights=1/0.02)
    print('\n\n\n\n\n')
    print(out_reflex.fit_report())
    print(x_min(out_reflex.best_values['b'],
                out_reflex.best_values['c'],
                out_reflex.best_values['c'],
                out_reflex.best_values['d']))
    plt.errorbar(data_set.alpha,data_set.ps, yerr=data_err[0] ,fmt=' h', label=str(dicke)+' Schichtdicke',c=c)
    plt.plot(np.arange(37,55,0.1),out_reflex.eval(x=np.arange(37,55,0.1)), label=str(dicke)+' Fit',c=c)

plt.xlabel(r'Winkel / $^\circ$', fontsize=24)
plt.ylabel(r'$R_p/R_s$', fontsize=24)
plt.xticks(fontsize=18)
plt.yticks(fontsize=18)
plt.xlim([37,53])
plt.legend(loc='best', fontsize=24)
plt.show()







[[Model]]
    Model(reflexion_fit)
[[Fit Statistics]]
    # function evals   = 141
    # data points      = 17
    # variables        = 5
    chi-square         = 0.223
    reduced chi-square = 0.019
[[Variables]]
    a:   0.39254194 +/- 0.010502 (2.68%) (init= 0.9)
    b:  -34.4534829 +/- 1.324938 (3.85%) (init= 0.3)
    c:   12.5208736 +/- 0.214422 (1.71%) (init= 1)
    d:   41.6413421 +/- 0.081433 (0.20%) (init= 43)
    e:  -2.37217622 +/- 0.019517 (0.82%) (init=-1)
[[Correlations]] (unreported correlations are <  0.100)
    C(b, c)                      = -0.991 
    C(c, d)                      = -0.982 
    C(b, d)                      =  0.982 
    C(a, d)                      = -0.839 
    C(a, c)                      =  0.798 
    C(a, b)                      = -0.741 
    C(a, e)                      = -0.542 
    C(c, e)                      = -0.140 
    C(d, e)                      =  0.101 

57.0047167861






[[Model]]
    Model(reflexion_fit)
[[Fit Statistics]]
  

In [262]:
def wellenzahl(x):
    return 1.515*(2*np.pi/(670*10**9))*np.sin(np.deg2rad(x))

In [263]:
for i in [51,48.5,45.8,45.3,44.1]:
    print(wellenzahl(i))

1.10413021062e-11
1.06407892307e-11
1.01855082504e-11
1.00986843105e-11
9.8871818266e-12


In [258]:
np.sin(np.deg2rad([51,48.5,45.8,45.3,44.1]))

array([ 0.77714596,  0.74895572,  0.71691061,  0.71079947,  0.6959128 ])

In [259]:
1.515*(2*np.pi/(670*10**9))

1.4207501105040406e-11