In [307]:
from scipy import constants,misc as cs,misc
from glob import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from lmfit import models
import math

#Rutherfordstreuung

##Rutherfordsteuuformel
<br>
$\huge \huge \frac{d\sigma}{d\Omega} = 1.3 \cdot 10^{-3} \left( \frac{Z_1 Z_2}{E_0} \right) \frac{1}{sin^4\left(\frac{\theta}{2}\right)}$

<ul>
    <li>$\sigma$: Differentielle WQ
    <li>$\Theta$: Winkel
    <li>$Z_i$: Kernlagundszahl
    <li>E: Energie
</ul>   

In [308]:
def rutherfordsteuung(theta,Z_1,Z_2,E,b):
    return (Z_1*Z_2*cs.e**2)/(4*E*np.sin((3.14*theta-b)/360)**4)

In [309]:
file_list_gold = []
liste_gold = []
for i in glob('/home/arrow13/Git/FP/Rutherford/MessdatenRutherford/Gold/*.txt'):
    file_list_gold.append(i)

    
file_list_gold.sort()   
    
for i in file_list_gold:
    liste_gold.append(np.array(pd.read_csv(i,skiprows=0,delim_whitespace=2)).T)
    


In [310]:
for i in file_list_gold:
    print(i)

/home/arrow13/Git/FP/Rutherford/MessdatenRutherford/Gold/2.Messung-30Grad.txt
/home/arrow13/Git/FP/Rutherford/MessdatenRutherford/Gold/3.Messung-25Grad.txt
/home/arrow13/Git/FP/Rutherford/MessdatenRutherford/Gold/4.Messung-20Grad.txt
/home/arrow13/Git/FP/Rutherford/MessdatenRutherford/Gold/5.Messung-15Grad.txt
/home/arrow13/Git/FP/Rutherford/MessdatenRutherford/Gold/6.Messung-10Grad.txt
/home/arrow13/Git/FP/Rutherford/MessdatenRutherford/Gold/7.Messung-5Grad.txt
/home/arrow13/Git/FP/Rutherford/MessdatenRutherford/Gold/8.Messung0Grad.txt
/home/arrow13/Git/FP/Rutherford/MessdatenRutherford/Gold/9.Messung5Grad.txt
/home/arrow13/Git/FP/Rutherford/MessdatenRutherford/Gold/910.Messung10Grad.txt
/home/arrow13/Git/FP/Rutherford/MessdatenRutherford/Gold/911.Messung15Grad.txt
/home/arrow13/Git/FP/Rutherford/MessdatenRutherford/Gold/912.Messung20Grad.txt
/home/arrow13/Git/FP/Rutherford/MessdatenRutherford/Gold/913.Messung25Grad.txt
/home/arrow13/Git/FP/Rutherford/MessdatenRutherford/Gold/914.Mess

In [311]:
def poisson(x,A=2):
    return 180*((A**x/misc.factorial(x))*np.e**(-A))

In [312]:
mod_pos = models.Model(poisson)

In [313]:
print(len(liste_gold))

13


In [314]:
err = []
gold_fit_reports = []
gold_fit_pars = []
for i in liste_gold:
    if i[0].size < 1:
        continue
    err_temp = None
    err_temp = np.sqrt(i[1])
    err_temp = np.where(err_temp == 0, 1, err_temp)
    err.append(np.where(np.sqrt(i[1]) == 0, 1, np.sqrt(i[1])))
    pars = mod_pos.make_params()
    fit = mod_pos.fit(i[1],
                  pars,
                  A= np.sum(i[0]*i[1]/180),
                  #B=4
                  weights=1/err_temp,
                  x=i[0])
    gold_fit_reports.append(fit.fit_report())
    gold_fit_pars.append(np.array([fit.best_values,fit.chisqr]))
    fit.plot()
    plt.show()

In [315]:
for i in gold_fit_reports:
    print(i, "\n\n\n\n\n")

[[Model]]
    Model(poisson)
[[Fit Statistics]]
    # function evals   = 7
    # data points      = 8
    # variables        = 1
    chi-square         = 7.155
    reduced chi-square = 1.022
[[Variables]]
    A:   2.63197289 +/- 0.125664 (4.77%) (init= 2.622222)
[[Correlations]] (unreported correlations are <  0.100) 





[[Model]]
    Model(poisson)
[[Fit Statistics]]
    # function evals   = 7
    # data points      = 17
    # variables        = 1
    chi-square         = 7.338
    reduced chi-square = 0.459
[[Variables]]
    A:   9.33255011 +/- 0.163175 (1.75%) (init= 9.111111)
[[Correlations]] (unreported correlations are <  0.100) 





[[Model]]
    Model(poisson)
[[Fit Statistics]]
    # function evals   = 5
    # data points      = 27
    # variables        = 1
    chi-square         = 15.500
    reduced chi-square = 0.596
[[Variables]]
    A:   13.4884681 +/- 0.207408 (1.54%) (init= 13.47222)
[[Correlations]] (unreported correlations are <  0.100) 





[[Model]]
    Model(po

In [316]:
file_list_alu = []
liste_alu = []
for i in glob('/home/arrow13/Git/FP/Rutherford/MessdatenRutherford/Alu/*.txt'):
    file_list_alu.append(i)

    
file_list_alu.sort()    
    
for i in file_list_alu:
    liste_alu.append(np.array(pd.read_csv(i,skiprows=0,delim_whitespace=2)).T)
    


In [317]:
for i in file_list_alu:
    print(i)

/home/arrow13/Git/FP/Rutherford/MessdatenRutherford/Alu/1.txt
/home/arrow13/Git/FP/Rutherford/MessdatenRutherford/Alu/2.txt
/home/arrow13/Git/FP/Rutherford/MessdatenRutherford/Alu/3.txt
/home/arrow13/Git/FP/Rutherford/MessdatenRutherford/Alu/4.txt
/home/arrow13/Git/FP/Rutherford/MessdatenRutherford/Alu/5.txt
/home/arrow13/Git/FP/Rutherford/MessdatenRutherford/Alu/6.txt
/home/arrow13/Git/FP/Rutherford/MessdatenRutherford/Alu/7.txt
/home/arrow13/Git/FP/Rutherford/MessdatenRutherford/Alu/8.txt
/home/arrow13/Git/FP/Rutherford/MessdatenRutherford/Alu/9.txt
/home/arrow13/Git/FP/Rutherford/MessdatenRutherford/Alu/91.txt
/home/arrow13/Git/FP/Rutherford/MessdatenRutherford/Alu/92.txt
/home/arrow13/Git/FP/Rutherford/MessdatenRutherford/Alu/93.txt
/home/arrow13/Git/FP/Rutherford/MessdatenRutherford/Alu/94.txt


In [318]:
alu_fit_reports = []
alu_fit_pars = []
for i in liste_alu:
    if i[0].size < 1:
        continue
    err_temp = None
    err_temp = np.sqrt(i[1])
    err_temp = np.where(err_temp == 0, 1, err_temp)
    pars = mod_pos.make_params()
    fit = mod_pos.fit(i[1],
                  pars,
                  A= np.sum(i[0]*i[1]/180),
                  #B=4,
                  weights=1/err_temp,
                  x=i[0])
    alu_fit_reports.append(fit.fit_report())
    alu_fit_pars.append(np.array([fit.best_values,fit.chisqr]))
    fit.plot()
    plt.show()

In [319]:
for i in alu_fit_reports:
    print(i, "\n\n\n\n\n")

[[Model]]
    Model(poisson)
[[Fit Statistics]]
    # function evals   = 7
    # data points      = 2
    # variables        = 1
    chi-square         = 0.000
    reduced chi-square = 0.000
[[Variables]]
    A:   0.04046106 +/- 0.000167 (0.41%) (init= 0.03888889)
[[Correlations]] (unreported correlations are <  0.100) 





[[Model]]
    Model(poisson)
[[Fit Statistics]]
    # function evals   = 11
    # data points      = 13
    # variables        = 1
    chi-square         = 85.498
    reduced chi-square = 7.125
[[Variables]]
    A:   4.42602200 +/- 0.304756 (6.89%) (init= 2.577778)
[[Correlations]] (unreported correlations are <  0.100) 





[[Model]]
    Model(poisson)
[[Fit Statistics]]
    # function evals   = 9
    # data points      = 32
    # variables        = 1
    chi-square         = 23.188
    reduced chi-square = 0.748
[[Variables]]
    A:   19.0763671 +/- 0.258553 (1.36%) (init= 19.03889)
[[Correlations]] (unreported correlations are <  0.100) 





[[Model]]
    Mode

In [320]:
counts_gold = []
for i in gold_fit_pars:
    print(i[0]["A"])
    counts_gold.append(i[0]["A"])

2.63197289084
9.33255011146
13.4884681301
10.7643177925
10.4608224312
14.0690842775
15.9033132574
15.8315027463
15.5120929706
14.196437796
6.42009762971
0.710278647736
0.0714152482036


In [321]:
x = np.arange(-30,35,5)

In [322]:
def ruth(x,A,B):
    return A/(np.sin((((x-B)*np.pi)/180)/2)**4)

In [323]:
mod_ruth = models.Model(ruth)
pars_2 = mod_ruth.make_params()

In [324]:
out_2 = mod_ruth.fit(counts_gold,
                    pars_2,
                    A=0.0001,
                    B=0,
                    x=x)

In [325]:
out_2.plot()
plt.show()

In [326]:
plt.plot(x,ruth(x,0.00001,0))
plt.show()

In [327]:
counts_alu = []
for i in alu_fit_pars:
    print(i[0]["A"])
    counts_alu.append(i[0]["A"])

0.0404610693939
4.42602200433
19.0763670952
20.2869002051
20.4977673514
20.264467455
20.7795956766
20.1110804962
19.6439416953
18.1254990007
18.0762561143
5.4430527236
0.0939586721674


In [328]:
out_3 = mod_ruth.fit(counts_alu,
                    pars_2,
                    A=0.00000001,
                    B=0,
                    x=x)
print(out_3.fit_report())

[[Model]]
    Model(ruth)
[[Fit Statistics]]
    # function evals   = 3
    # data points      = 13
    # variables        = 2
    chi-square         = inf
    reduced chi-square = inf
[[Variables]]
    A:   1.0000e-08 +/- 0        (0.00%) (init= 1e-08)
    B:   1.4901e-08 +/- 0        (0.00%) (init= 0)
[[Correlations]] (unreported correlations are <  0.100)


In [329]:
out_3.plot()
plt.show()

In [330]:
plt.plot(x,counts_gold, 'r.')
plt.legend(loc = 'best', fontsize = 22)
plt.tick_params(labelsize= 22)
plt.ylabel(r"Counts/s", fontsize = 26)
plt.xlabel("theta$/^{\circ}$", fontsize = 26)
plt.show()

/home/arrow13/anaconda3/lib/python3.4/site-packages/matplotlib/axes/_axes.py:475: UserWarning: No labelled objects found. Use label='...' kwarg on individual plots.
  warnings.warn("No labelled objects found. "


In [331]:
plt.plot(x,counts_alu, 'r.')
plt.legend(loc = 'best', fontsize = 22)
plt.tick_params(labelsize= 22)
plt.ylabel(r"Counts/s", fontsize = 26)
plt.xlabel("theta$/^{\circ}$", fontsize = 26)
plt.show()

/home/arrow13/anaconda3/lib/python3.4/site-packages/matplotlib/axes/_axes.py:475: UserWarning: No labelled objects found. Use label='...' kwarg on individual plots.
  warnings.warn("No labelled objects found. "


In [332]:
print(x.size)
len(counts_alu)

13


13

In [333]:
for i in liste_alu:
    a= np.sum(i[1])
    print(a)
    print(i)

180
[[  0   1]
 [173   7]]
101
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
 [ 3  4 11 16 19 16 12 11  2  4  1  1  1]]
180
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31]
 [ 0  0  0  0  0  0  0  0  0  2  1  2  3  4 12  6 18 18 20 14 24 12 12  8
   6  5  4  2  1  5  0  1]]
180
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31]
 [ 0  0  0  0  0  0  0  0  0  0  0  2  5  5  4  5 10 14 13 16 20 18 17 10
  15  9  4  5  5  1  1  1]]
180
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32 33 34]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  2  2  8  9 11 15 18 18 15 10 10  8
  13 11  9  3  3  4  2  3  2  1  2]]
180
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32 33 34 35 36]
 [ 0  0  0  0  0  0  0  0  0  0  1  2  2  5  9  6  6 15 16  9 18 17 17  8
  13 15  8  2  4  1  2  1  2  0  0  0  1]]
180
[[ 0

In [334]:
for i in liste_gold:
    a= np.sum(i[1])
    print(a)
    print(i)

180
[[ 0  1  2  3  4  5  6  7]
 [18 33 35 40 31 14  8  1]]
180
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 1  0  1  4  4 13 11 17 26 24 19 21 16 10  6  3  4]]
180
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26]
 [ 0  0  0  0  0  4  3  2  6 12 14 13 26 15 17 16 13 14  6  8  3  2  1  3
   1  0  1]]
180
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
 [ 0  0  0  0  4  4  8 16 18 17 19 15 18 22 13 12  7  2  2  1  1  0  0  1]]
180
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
 [ 0  0  1  0  1  5  9 16 16 25 15 19 22 15 13  5  2  9  3  0  2  1  0  1]]
180
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25]
 [ 0  0  0  0  0  1  3  3  7  6 15 15 19 10 18 15 17 16 16  6  5  2  3  1
   1  1]]
180
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26]
 [ 0  0  0  0  0  0  0  0  2  5  6 15  9 12 20 17 18 13 18 11 10  9  7  5
   1  